### PR TITLE
- Add `meta.type` to rules

### PR DESCRIPTION
**Pull request by brettz9**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Documentation update
[ ] Bug fix
[ ] New feature
[x] Other, please explain:  Add standard metadata.

**What changes did you make? (Give an overview)**

- Add `meta.type` to rules ("layout" for all rules but `no-callback-literal` which is set to "suggestion")
- Adhere to standard linting on README example
- Add `.editorconfig` to prep. IDEs for proper indentation before lint checking/fixing

**Which issue (if any) does this pull request address?**

N/A

**Is there anything you'd like reviewers to focus on?**

While `meta.type` is normally used with [`eslint --fix-type`](https://eslint.org/docs/user-guide/command-line-interface#fix-type) (and you currently have no fixers), as official meta-data exposed to formatters, I am planning to use it in my badge formatter (which I expect to release soon); it can show a summary of linting problems by type, e.g., "layout", "problem", or "suggestion". Regardless of how it may end up being used, it shouldn't hurt to clarify the intent of the rule by expressing `meta.type`.

### CODE REVIEW

**Comment by brettz9** [comment]
Bump..

**Comment by brettz9** [comment]
Any chance you can take a look? I don't think this change should be very controversial...

**Review by feross — APPROVED** [review]
LGTM

**Comment by brettz9** [comment]
Thank you. FWIW, the tool I mentioned is functional: https://github.com/brettz9/eslint-formatter-badger

**Pull request merged**
